server:
  port: 8888
  compression:
    min-response-size: 1024
    enabled: true

spring:
  # 数据源配置
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/user?useSSL=false&serverTimezone=CTT&characterEncoding=UTF8
    username: root

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
    auto: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      # 最大支持文件大小
      max-file-size: 1000MB
      # 最大支持请求大小
      max-request-size: 1000MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

