server:
  port: 8888
  compression:
    min-response-size: 1024
    enabled: true

spring:
  # 数据源配置
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/user?useSSL=false&serverTimezone=CTT&characterEncoding=UTF8
    username: root

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
    auto: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      # 最大支持文件大小
      max-file-size: 1000MB
      # 最大支持请求大小
      max-request-size: 1000MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml


#APPID
wechat:
appid=wxdf4a5ec5661b9589
#secret
appsecret=64a5df9547f60ccb2e2cc8c972d3b280
token=weixin
#回调地址（内网穿透地址）
server=http://elwin.*************.com
#获取二维码
qrCodeUrl: https://api.weixin.qq.com/cgi-bin/qrcode/create?access_token=TOKEN
#基础接口的token
tokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
#获取openId
openIdUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=APPSECRET&code=CODE&grant_type=authorization_code
#获取用户
userInfoUrl: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
#通过ticket获取二维码
showqrcode: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=TICKET


